#!/bin/bash

curl -A "Slackbot/1.0" -X POST -d 'token=8QGp1HZqk6A2Zbmzsa0vdxvd&team_id=T029XH96J&team_domain=datto&channel_id=D398YSPC3&channel_name=directmessage&user_id=U39DH8M37&user_name=memeny&command=%2Fdank&text=asdf&response_url=https%3A%2F%2Fhooks.slack.com%2Fcommands%2FT029XH96J%2F114103278389%2FOJQIfQmun1SjXqJGTQzuMCDP' http://localhost:8080 --header "application/x-www-form-urlencoded"
